### PR TITLE
Add support for limesdr

### LINKED ISSUE #174: Add support for LimeSDR
This tool would really improve the usability of LimeSDR.
SoapySDR or GR might be a good start.

### PR DESCRIPTION
**Pull request by jopohl**
This adds support for LimeSDR to fix #174 

- [x] wrap save method
- [x] Cython Wrapper + Test methods for each
   - [x] Sample Rate
   - [x] Gain
   - [x] Center Freq
   - [x] Bandwidth
   - [x] Antenna
   - [x] Temperature
   - [x] RX Stream
   - [x] TX Stream
- [x] adapt config.py for LimeSDR limits
- [x] Add Python Class
  - [x] refactor ``` process_command ``` 
     - [x] use enum for commands
     - [x] use generic ref for native lib in base class
     - [x] make method names configurable via defaultdict, if None/Unspupported -> Do nothing
  - [x] Mehod for receive
  - [x] Method for send
  - [x] multiprocessing communication
- [x] Fix: Sending sometimes stops before iteration is complete
- [x] Adapt GUI
   - [x] Make channel selectable
   - [x] Make antenna selectable
- [x] Tests
   - [x] test receive
      - [x] Linux
      - [x] Windows
   - [x] test send
      - [x] Linux
      - [x] Windows

### CODE REVIEW

**Comment by fede2cr** [comment]
I'm testing this but I cannot get it to work on the spectrum analyzer, or get any packets with the sniff protocol.
It it finding the card as it is showing the chip temperature.
Any settings you can recommend to test it?

**Comment by jopohl** [comment]
What Firmware Version are you using? For me, that is:

```
$ LimeUtil --info
######################################################
## LimeSuite information summary
######################################################

Version information:
  Library version:	v17.03.0-g29d986b7
  Build timestamp:	2017-04-03
  Interface version:	v2017.3.0
  Binary interface:	17.03-1
```
In addition, please tell me:
- What is your OS?
- Does the spectrum analyzer work in LimeSuite for you?

**Comment by andynoack** [comment]
Could you try a higher gain value? For me, 90 works fine

**Comment by jopohl** [comment]
You may need to set your gain a bit higher e.g. to 60.

**Comment by fede2cr** [comment]
######################################################
## LimeSuite information summary
######################################################

Version information:
  Library version:	v17.03.0-gd4a71aaa
  Build timestamp:	2017-04-12
  Interface version:	v2017.3.0
  Binary interface:	17.03-1

Running on Arch Linux. I'm preparing a fresh Ubuntu 16.04 to test here also.
I can use the spectrum analyzer on QSpectrumAnalyzer. Will try with LimeSuite.
I set a gain of 90, as well as 60, and 20 and it just shows a black diagonal.

**Comment by jopohl** [comment]
@fede2cr I also use Arch Linux, so that should work.

Can you delete your local clone and clone again? Sometimes files get cached that prevent a proper recompile of the device extensions.

**Pull request merged**
