### PR TITLE
Don't pin the upper bound of Cython dependency

### LINKED ISSUE #1087: Support Cython 3.0+
In Fedora Linux, we've successfully built `urh` with Cython 3.0.5 (see [build log](https://download.copr.fedorainfracloud.org/results/churchyard/cython-3-forced/fedora-rawhide-x86_64/06624196-urh/builder-live.log.gz) for details).
Would you consider unpinning the requirement on `Cython < 3` in the project? I can send the PR.

### PR DESCRIPTION
**Pull request by befeleme**
Closes  #1087

### CODE REVIEW

**Review by jopohl — CHANGES_REQUESTED** [review]
Please also remove the pin from [requirements.txt](https://github.com/jopohl/urh/blob/64df7856802800f862e4ff14bb1bac4ec1abaee2/data/requirements.txt#L4C13-L4C13).

**Comment by befeleme** [comment]
Fixed in the amended commit.

**Comment by jopohl** [comment]
Thanks, CI is now failing though as reported #1063.

**Comment by jopohl** [comment]
Fixed via #1099

**Pull request closed without merging**
