### PR TITLE
module import needs `__init__.py`

### PR DESCRIPTION
**Pull request by hamarituc**
This PR fixes a `ModuleNotFoundError` exception during install.

```
python3.10 setup.py --without-airspy --without-bladerf --with-hackrf --without-limesdr --with-plutosdr --with-rtlsdr --without-sdrplay --without-usrp build -j 5
Traceback (most recent call last):
  File "/var/tmp/portage/net-wireless/urh-2.9.3/work/urh-2.9.3/setup.py", line 19, in <module>
    from src.urh.dev.native import ExtensionHelper
ModuleNotFoundError: No module named 'src.urh'
```

See https://bugs.gentoo.org/888627 and https://github.com/gentoo/gentoo/pull/28848 for more details. A similar problem was reported in #416. But it seems the issue doesn't occur under any circumstances and it is unclear when it happens an when not. But adding `__init__.py` fixes it in any case.

### CODE REVIEW

**Comment by jopohl** [comment]
Can't reproduce on Arch Linux, running this command
```
python3.10 setup.py --without-airspy --without-bladerf --with-hackrf --without-limesdr --with-plutosdr --with-rtlsdr --without-sdrplay --without-usrp build -j 5
```
on a fresh clone on master branch works for me. The proposed solution declares `src` as a Python package which is not intended. 

Does it help when you set the PYTHONPATH explicitly, i.e,
```
PYTHONPATH=. python3.10 setup.py --without-airspy --without-bladerf --with-hackrf --without-limesdr --with-plutosdr --with-rtlsdr --without-sdrplay --without-usrp build -j 5
```

**Comment by ZeroChaos-** [comment]
@hamarituc Can you give any tips on how to reproduce this?  I can't reproduce it either.

**Comment by hamarituc** [comment]
> @hamarituc Can you give any tips on how to reproduce this? I can't reproduce it either.

There was a python package on my system which (incorrectly) installed some modules in `/usr/lib/python3.10/site-packages/src`. This path has a higher precedence than the source repository. Consider this as an oddity of my system. Sorry for the noise.

**Comment by ZeroChaos-** [comment]
Awesome, glad you figured it out.

**Pull request closed without merging**
