### PR TITLE
add b before data string

### LINKED ISSUE #845: rfcat not sending
Hi,i have problem with send data via rfcat.Rfcat now use bytes instead of string to send data..Here is error:

TypeError                                 Traceback (most recent call last)
/usr/local/lib/python3.9/dist-packages/rflib/__init__.py in <module>
----> 1 d.RFxmit('\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\')

/usr/local/lib/python3.9/dist-packages/rflib/chipcon_nic.py in RFxmit(self, data, repeat, offset)
   1125         waitlen += repeat * (len(data) - offset)
   1126         wait = USB_TX_WAIT * ((old_div(waitlen, RF_MAX_TX_BLOCK)) + 1)
-> 1127         self.send(APP_NIC, NIC_XMIT, b"%s" % struct.pack("<HHH",len(data),repeat,offset)+data, wait=wait)
   1128 
   1129     def RFxmitLong(self, data, doencoding=True):

TypeError: can't concat str to bytes

sending command shoul be: d.RFxmit(b'\\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa\xaa')

Thanks for help

### PR DESCRIPTION
**Pull request by andynoack**
Fix #845

### CODE REVIEW

**Comment by jopohl** [comment]
Nice fix, just two questions about this:
1. Can we be sure that this will not break the rfcat plugin for users with an old, i.e., the python2 version of rfcat?
2. Will this fix cause problems on our end once/if https://github.com/atlas0fd00m/rfcat/pull/87 gets merged?

**Comment by andynoack** [comment]
Good point, we cannot be sure this does not break anything. Putting the information as bytes with (b'...') should not make much difference, even for the old interface. What do you suggest?

**Comment by jopohl** [comment]
I cannot test this right now, but in worst-case we might transmit an additional "b" for the old version. 

Normally, I would suggest to make a simple if-construct and check for the version of rfcat. Unfortunately, the versioning seems to to pretty useless: https://github.com/atlas0fd00m/rfcat/releases/tag/v1.0.0

Another pattern would be to use the "ask for excuse instead of permission" approach and do something like:

```python
self.prefix = None
....

# determine the prefix on first call
if self.prefix is None:
  try:
    "d.RFxmit({})"   # use the old version
    self.prefix = ""
  except TypeError:
   "d.RFxmit(b{})"   # use the new version
   self.prefix = "b"
else:
  "d.RFxmit({}{})".format(self.prefix, data) 
```

**Comment by pickeditmate** [comment]
rfcat is running on python 3 now anyway, i've not got python 2.7 even installed and rfcat is running smoothly as atlas has made the latest release work and is asking for feedback.

**Comment by jopohl** [comment]
If rfcat is Python3 now, we might simplify the RfCat plugin a lot by just importing rfcat and calling its methods directly instead of wrapping the rfcat executable.

**Comment by andynoack** [comment]
I am totally okay with just adding the 'b', but I don't think it is worth the effort to refactor the plugin at the moment. Setting up software and hardware for testing is what currently prevents me from elaborating a nice and clean solution, having in mind that only very few people will take notice.

**Comment by pickeditmate** [comment]
I tried the rfcat fix branch and also tried, before that, to just add the b to the string, both with no success, I'm begining to wonder if I'm missing something else on my system following those tests. 

Could someone confirm what is meant to be seen after pressing the button as I get no light as I usually do when transmitting on the yardstick.

My environment is as follows:
Windows 10 x64
Python 3.9
rfcat latest version (python 3 compatible)

**Review by chrystianrgs — APPROVED** [review]

**Pull request merged**
